### ISSUE TITLE
This is invoked twice

### ISSUE THREAD

**Issue by AlexKap23** [Sosa09/TicTacToe#6]
https://github.com/Sosa09/TicTacToe/blob/701d6f1231e8ede2de63f518c140059e2826ab09/TicTacToe/UIExperience.cs#L37
On line 32 of Program.cs you are invoking UIExperience.RefreshInterface(grid); and you don't save the value.

On the next line you invoke method DesignGameInterface which invokes RefreshInterface() again and this time saves the result. 

Can't you save it from the first invocation and avoid the second one?

**Comment by Sosa09** [comment]
Actually i think the refresh on line 32 is not required it was there since the beginning  and i did analyzed correctly to check if it was wstll required or not. 

after removing that line it 's works fine/ now it is only invoked from the UI class i've also set the access modifier for RefreshInterface  to private
